"""Added Time

Revision ID: f70a9b315e55
Revises: 4ac2fca490b5
Create Date: 2023-10-28 21:06:05.916764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70a9b315e55'
down_revision = '4ac2fca490b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenditure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    with op.batch_alter_table('expenditure', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
