"""Added Savings Table

Revision ID: ff529d78addd
Revises: f70a9b315e55
Create Date: 2023-10-29 14:11:30.015348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff529d78addd'
down_revision = 'f70a9b315e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_amount', sa.Float(), nullable=True))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=True))
        batch_op.drop_column('goal_amount')

    # ### end Alembic commands ###
